### ISSUE TITLE
Texture Alignment

### ISSUE THREAD

**Issue by NCC-Lykos** [NCC-Lykos/Chisel#4]
The texture alignment between rfEdit, and other Genesis Editors and Chisel is off.

Chisel allows align to face or world, but sometimes it does not work, and it does not always translate back to rfedit for backwards compatibility.

**Genesis Editor & Chisel Compatibility TODO**

- [x] Texture Scale
- [x] Texture Shift
- [x] Texture Rotation
- [x] Texture Locking
- [x] Writing proper data back to the 3DT in v1.32 Format

**Comment by mlct84** [comment]
Writing proper data back to the 3DT in v1.32 Format is supported.

**Comment by NCC-Lykos** [comment]
Done!
